// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.26.0
// 	protoc        v3.18.1
// source: wallet_message.proto

package walletpb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type CreateWalletRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *CreateWalletRequest) Reset() {
	*x = CreateWalletRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_wallet_message_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CreateWalletRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateWalletRequest) ProtoMessage() {}

func (x *CreateWalletRequest) ProtoReflect() protoreflect.Message {
	mi := &file_wallet_message_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateWalletRequest.ProtoReflect.Descriptor instead.
func (*CreateWalletRequest) Descriptor() ([]byte, []int) {
	return file_wallet_message_proto_rawDescGZIP(), []int{0}
}

type WalletBaseResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	BlockchainAddress *string `protobuf:"bytes,1,req,name=blockchain_address,json=blockchainAddress" json:"blockchain_address,omitempty"`
}

func (x *WalletBaseResponse) Reset() {
	*x = WalletBaseResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_wallet_message_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *WalletBaseResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WalletBaseResponse) ProtoMessage() {}

func (x *WalletBaseResponse) ProtoReflect() protoreflect.Message {
	mi := &file_wallet_message_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WalletBaseResponse.ProtoReflect.Descriptor instead.
func (*WalletBaseResponse) Descriptor() ([]byte, []int) {
	return file_wallet_message_proto_rawDescGZIP(), []int{1}
}

func (x *WalletBaseResponse) GetBlockchainAddress() string {
	if x != nil && x.BlockchainAddress != nil {
		return *x.BlockchainAddress
	}
	return ""
}

var File_wallet_message_proto protoreflect.FileDescriptor

var file_wallet_message_proto_rawDesc = []byte{
	0x0a, 0x14, 0x77, 0x61, 0x6c, 0x6c, 0x65, 0x74, 0x5f, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65,
	0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x05, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0x15, 0x0a,
	0x13, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x57, 0x61, 0x6c, 0x6c, 0x65, 0x74, 0x52, 0x65, 0x71,
	0x75, 0x65, 0x73, 0x74, 0x22, 0x43, 0x0a, 0x12, 0x57, 0x61, 0x6c, 0x6c, 0x65, 0x74, 0x42, 0x61,
	0x73, 0x65, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x2d, 0x0a, 0x12, 0x62, 0x6c,
	0x6f, 0x63, 0x6b, 0x63, 0x68, 0x61, 0x69, 0x6e, 0x5f, 0x61, 0x64, 0x64, 0x72, 0x65, 0x73, 0x73,
	0x18, 0x01, 0x20, 0x02, 0x28, 0x09, 0x52, 0x11, 0x62, 0x6c, 0x6f, 0x63, 0x6b, 0x63, 0x68, 0x61,
	0x69, 0x6e, 0x41, 0x64, 0x64, 0x72, 0x65, 0x73, 0x73, 0x42, 0x0d, 0x5a, 0x0b, 0x2e, 0x2f, 0x3b,
	0x77, 0x61, 0x6c, 0x6c, 0x65, 0x74, 0x70, 0x62,
}

var (
	file_wallet_message_proto_rawDescOnce sync.Once
	file_wallet_message_proto_rawDescData = file_wallet_message_proto_rawDesc
)

func file_wallet_message_proto_rawDescGZIP() []byte {
	file_wallet_message_proto_rawDescOnce.Do(func() {
		file_wallet_message_proto_rawDescData = protoimpl.X.CompressGZIP(file_wallet_message_proto_rawDescData)
	})
	return file_wallet_message_proto_rawDescData
}

var file_wallet_message_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_wallet_message_proto_goTypes = []interface{}{
	(*CreateWalletRequest)(nil), // 0: proto.CreateWalletRequest
	(*WalletBaseResponse)(nil),  // 1: proto.WalletBaseResponse
}
var file_wallet_message_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_wallet_message_proto_init() }
func file_wallet_message_proto_init() {
	if File_wallet_message_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_wallet_message_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CreateWalletRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_wallet_message_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*WalletBaseResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_wallet_message_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_wallet_message_proto_goTypes,
		DependencyIndexes: file_wallet_message_proto_depIdxs,
		MessageInfos:      file_wallet_message_proto_msgTypes,
	}.Build()
	File_wallet_message_proto = out.File
	file_wallet_message_proto_rawDesc = nil
	file_wallet_message_proto_goTypes = nil
	file_wallet_message_proto_depIdxs = nil
}
