// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.2.0
// - protoc             v3.18.1
// source: wallet_management_service.proto

package walletpb

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// WalletManagementClient is the client API for WalletManagement service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type WalletManagementClient interface {
	Create(ctx context.Context, in *CreateWalletRequest, opts ...grpc.CallOption) (*WalletBaseResponse, error)
}

type walletManagementClient struct {
	cc grpc.ClientConnInterface
}

func NewWalletManagementClient(cc grpc.ClientConnInterface) WalletManagementClient {
	return &walletManagementClient{cc}
}

func (c *walletManagementClient) Create(ctx context.Context, in *CreateWalletRequest, opts ...grpc.CallOption) (*WalletBaseResponse, error) {
	out := new(WalletBaseResponse)
	err := c.cc.Invoke(ctx, "/proto.WalletManagement/Create", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// WalletManagementServer is the server API for WalletManagement service.
// All implementations should embed UnimplementedWalletManagementServer
// for forward compatibility
type WalletManagementServer interface {
	Create(context.Context, *CreateWalletRequest) (*WalletBaseResponse, error)
}

// UnimplementedWalletManagementServer should be embedded to have forward compatible implementations.
type UnimplementedWalletManagementServer struct {
}

func (UnimplementedWalletManagementServer) Create(context.Context, *CreateWalletRequest) (*WalletBaseResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Create not implemented")
}

// UnsafeWalletManagementServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to WalletManagementServer will
// result in compilation errors.
type UnsafeWalletManagementServer interface {
	mustEmbedUnimplementedWalletManagementServer()
}

func RegisterWalletManagementServer(s grpc.ServiceRegistrar, srv WalletManagementServer) {
	s.RegisterService(&WalletManagement_ServiceDesc, srv)
}

func _WalletManagement_Create_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateWalletRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(WalletManagementServer).Create(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/proto.WalletManagement/Create",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(WalletManagementServer).Create(ctx, req.(*CreateWalletRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// WalletManagement_ServiceDesc is the grpc.ServiceDesc for WalletManagement service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var WalletManagement_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "proto.WalletManagement",
	HandlerType: (*WalletManagementServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Create",
			Handler:    _WalletManagement_Create_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "wallet_management_service.proto",
}
