// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.2.0
// - protoc             v3.18.1
// source: transaction_management_service.proto

package transactionpb

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// TransactionManagementClient is the client API for TransactionManagement service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type TransactionManagementClient interface {
	Create(ctx context.Context, in *CreateTransactionRequest, opts ...grpc.CallOption) (*TransactionBaseResponse, error)
}

type transactionManagementClient struct {
	cc grpc.ClientConnInterface
}

func NewTransactionManagementClient(cc grpc.ClientConnInterface) TransactionManagementClient {
	return &transactionManagementClient{cc}
}

func (c *transactionManagementClient) Create(ctx context.Context, in *CreateTransactionRequest, opts ...grpc.CallOption) (*TransactionBaseResponse, error) {
	out := new(TransactionBaseResponse)
	err := c.cc.Invoke(ctx, "/proto.TransactionManagement/Create", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// TransactionManagementServer is the server API for TransactionManagement service.
// All implementations should embed UnimplementedTransactionManagementServer
// for forward compatibility
type TransactionManagementServer interface {
	Create(context.Context, *CreateTransactionRequest) (*TransactionBaseResponse, error)
}

// UnimplementedTransactionManagementServer should be embedded to have forward compatible implementations.
type UnimplementedTransactionManagementServer struct {
}

func (UnimplementedTransactionManagementServer) Create(context.Context, *CreateTransactionRequest) (*TransactionBaseResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Create not implemented")
}

// UnsafeTransactionManagementServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to TransactionManagementServer will
// result in compilation errors.
type UnsafeTransactionManagementServer interface {
	mustEmbedUnimplementedTransactionManagementServer()
}

func RegisterTransactionManagementServer(s grpc.ServiceRegistrar, srv TransactionManagementServer) {
	s.RegisterService(&TransactionManagement_ServiceDesc, srv)
}

func _TransactionManagement_Create_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateTransactionRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TransactionManagementServer).Create(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/proto.TransactionManagement/Create",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TransactionManagementServer).Create(ctx, req.(*CreateTransactionRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// TransactionManagement_ServiceDesc is the grpc.ServiceDesc for TransactionManagement service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var TransactionManagement_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "proto.TransactionManagement",
	HandlerType: (*TransactionManagementServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Create",
			Handler:    _TransactionManagement_Create_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "transaction_management_service.proto",
}
